# Generated by Django 5.0.3 on 2024-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afeciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afeccion', models.CharField(help_text='Afección o enfermedad', max_length=80, verbose_name='Afeción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Afección enfermedad',
                'verbose_name_plural': 'Afecciones o Enfermedades',
                'db_table': 'plantas_afecciones',
                'ordering': ['afeccion'],
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(help_text='Genero', max_length=20, verbose_name='Genero')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Genenros',
                'db_table': 'plantas_generos',
                'ordering': ['genero'],
            },
        ),
    ]
