# Generated by Django 5.0.3 on 2024-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadesAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(help_text='Enfermedad', max_length=80, verbose_name='Enfermedad')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'plantas_enfermedad_adicinales',
                'ordering': ['enfermedad'],
            },
        ),
    ]
