# Generated by Django 5.0.3 on 2024-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_enfermedadesadicionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hipersensibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(help_text='Componente', max_length=80, verbose_name='Componente')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes hipersensibilidad',
                'db_table': 'plantas_componentes_hipersensibilidad',
                'ordering': ['componente'],
            },
        ),
        migrations.AlterModelOptions(
            name='enfermedadesadicionales',
            options={'ordering': ['enfermedad'], 'verbose_name': 'Enfermedad', 'verbose_name_plural': 'Enfermedades Adicionales'},
        ),
    ]
